//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiqueSalon.AppDataFolder.ModelFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class AntiqueTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AntiqueTable()
        {
            this.RentTable = new HashSet<RentTable>();
            this.СollectionTable = new HashSet<СollectionTable>();
        }
    
        public int PersonalNumberAntique { get; set; }
        public string NameAntique { get; set; }
        public int PNTypeAntique { get; set; }
        public System.DateTime DatepurchaseAntique { get; set; }
        public decimal PriceAntique { get; set; }
        public Nullable<decimal> EvaluationPriceAntique { get; set; }
        public bool InsuranceAntique { get; set; }
        public string HistoryAntique { get; set; }
        public int PNWorker { get; set; }
    
        public virtual TypeAntiqueTable TypeAntiqueTable { get; set; }
        public virtual WorkerTable WorkerTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RentTable> RentTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<СollectionTable> СollectionTable { get; set; }
    }
}
