//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiqueSalon.AppDataFolder.ModelFolder
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AntiqueSalonDataBaseEntities : DbContext
    {
        public AntiqueSalonDataBaseEntities()
            : base("name=AntiqueSalonDataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AntiqueTable> AntiqueTable { get; set; }
        public virtual DbSet<RentTable> RentTable { get; set; }
        public virtual DbSet<RoleTable> RoleTable { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TypeAntiqueTable> TypeAntiqueTable { get; set; }
        public virtual DbSet<WorkerTable> WorkerTable { get; set; }
        public virtual DbSet<СollectionTable> СollectionTable { get; set; }
    }
}
