//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiqueSalon.AppDataFolder.ModelFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class RentTable
    {
        public int PersonalNumberRent { get; set; }
        public string SurnameRent { get; set; }
        public string NameRent { get; set; }
        public string MiddlenameRent { get; set; }
        public System.DateTime DatestartRent { get; set; }
        public Nullable<System.DateTime> DatestopRent { get; set; }
        public int PNWorker { get; set; }
        public int PNAntique { get; set; }
    
        public virtual AntiqueTable AntiqueTable { get; set; }
        public virtual WorkerTable WorkerTable { get; set; }
    }
}
