//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AntiqueSalon.AppDataFolder.ModelFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class СollectionTable
    {
        public int PersonalNumberCollection { get; set; }
        public int PNAntique { get; set; }
    
        public virtual AntiqueTable AntiqueTable { get; set; }
    }
}
